/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import simulador.compraevenda.java.Categoria;
import simulador.compraevenda.java.Controller;
import simulador.compraevenda.java.Fornecedores;
import simulador.compraevenda.java.Produto;
import simulador.compraevenda.java.Unidade;

/**
 *
 * @author CONDUCTOR\saulo.terceiro
 */
public class AdicionarProduto extends ControllerJFrame {

    public AdicionarProduto(Controller controller) {
        super(controller);
        initComponents();
    }
    

    /**
     * Creates new form AdicionarProduto
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        codigoDescricao = new javax.swing.JLabel();
        codigoEntrada = new javax.swing.JTextField();
        nomeDescricao = new javax.swing.JLabel();
        nomeEntrada = new javax.swing.JTextField();
        fornecedorDescricao = new javax.swing.JLabel();
        fornecedorEntrada = new javax.swing.JTextField();
        precoDescricao = new javax.swing.JLabel();
        precoEntrada = new javax.swing.JTextField();
        qtdDescricao = new javax.swing.JLabel();
        qtdEntrada = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        categoriaEntrada = new javax.swing.JTextField();
        categoriaDescricao = new javax.swing.JLabel();
        categoriaDescricao1 = new javax.swing.JLabel();
        unidadeEntrada = new javax.swing.JTextField();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Adicionar Produto");

        codigoDescricao.setText("Codigo:");

        codigoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEntradaActionPerformed(evt);
            }
        });

        nomeDescricao.setText("Nome:");

        nomeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEntradaActionPerformed(evt);
            }
        });

        fornecedorDescricao.setText("Codigo Fornecedor:");

        fornecedorEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorEntradaActionPerformed(evt);
            }
        });

        precoDescricao.setText("Preço:");

        precoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoEntradaActionPerformed(evt);
            }
        });

        qtdDescricao.setText("Qtd:");

        qtdEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdEntradaActionPerformed(evt);
            }
        });

        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        categoriaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaEntradaActionPerformed(evt);
            }
        });

        categoriaDescricao.setText("Categoria:");

        categoriaDescricao1.setText("Unidade:");

        unidadeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadeEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qtdDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdEntrada))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(precoDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoEntrada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeDescricao)
                        .addGap(18, 18, 18)
                        .addComponent(nomeEntrada))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigoDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fornecedorDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fornecedorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaDescricao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Enviar)
                    .addComponent(jButton1))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoriaDescricao)
                        .addComponent(categoriaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoDescricao)
                        .addComponent(codigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDescricao)
                    .addComponent(nomeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoriaDescricao1)
                        .addComponent(unidadeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fornecedorDescricao)
                        .addComponent(fornecedorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoDescricao)
                    .addComponent(precoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdDescricao)
                    .addComponent(qtdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enviar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEntradaActionPerformed

    private void nomeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEntradaActionPerformed

    private void fornecedorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorEntradaActionPerformed

    private void precoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoEntradaActionPerformed

    private void qtdEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtdEntradaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GerenciarProduto gp = new GerenciarProduto(controller);
        this.inicializarCena(gp, this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        int codigoProduto = Integer.valueOf(codigoEntrada.getText());
        int codigoFornecedor =Integer.valueOf(fornecedorEntrada.getText());
        int codigoCategoria =Integer.valueOf(categoriaEntrada.getText());
        Fornecedores fornecedor = this.controller.getFornecedorCodigo(codigoFornecedor);
        Categoria categoria = this.controller.getCategoriaCodigo(codigoCategoria);
        double preco = Double.valueOf(precoEntrada.getText());
        int qtd = Integer.valueOf(qtdEntrada.getText());
        int codigoUnidade = Integer.valueOf(unidadeEntrada.getText());
        Unidade unidade = controller.getUnidaedCodigo(codigoUnidade);
        
        Produto novoProduto = new Produto(categoria,codigoProduto,fornecedor,nomeEntrada.getText(),preco,qtd,unidade);
        
        controller.adicionarProduto(novoProduto);
    }//GEN-LAST:event_EnviarActionPerformed

    private void categoriaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaEntradaActionPerformed

    private void unidadeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadeEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadeEntradaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel categoriaDescricao;
    private javax.swing.JLabel categoriaDescricao1;
    private javax.swing.JTextField categoriaEntrada;
    private javax.swing.JLabel codigoDescricao;
    private javax.swing.JTextField codigoEntrada;
    private javax.swing.JLabel fornecedorDescricao;
    private javax.swing.JTextField fornecedorEntrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nomeDescricao;
    private javax.swing.JTextField nomeEntrada;
    private javax.swing.JLabel precoDescricao;
    private javax.swing.JTextField precoEntrada;
    private javax.swing.JLabel qtdDescricao;
    private javax.swing.JTextField qtdEntrada;
    private javax.swing.JTextField unidadeEntrada;
    // End of variables declaration//GEN-END:variables
}
