/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import simulador.compraevenda.java.Controller;
import simulador.compraevenda.java.Fornecedores;

/**
 *
 * @author CONDUCTOR\saulo.terceiro
 */
public class AdicionarFornecedor extends ControllerJFrame {

    public AdicionarFornecedor(Controller controller) {
        super(controller);
        initComponents();
    }

    /**
     * Creates new form AdicionarFornecedor
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoDescricao = new javax.swing.JLabel();
        codigoEntrada = new javax.swing.JTextField();
        nomeDescricao = new javax.swing.JLabel();
        nomeEntrada = new javax.swing.JTextField();
        fornecedorDescricao = new javax.swing.JLabel();
        cpfEntrada = new javax.swing.JTextField();
        precoDescricao = new javax.swing.JLabel();
        telefoneEntrada = new javax.swing.JTextField();
        qtdDescricao = new javax.swing.JLabel();
        voltar1 = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        emailEntrada = new javax.swing.JTextField();
        nomeDescricao1 = new javax.swing.JLabel();
        enderecoEntrada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Adicionar Fornecedor ");

        codigoDescricao.setText("Codigo:");

        codigoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEntradaActionPerformed(evt);
            }
        });

        nomeDescricao.setText("Nome:");

        nomeEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeEntradaActionPerformed(evt);
            }
        });

        fornecedorDescricao.setText("CPF:");

        cpfEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfEntradaActionPerformed(evt);
            }
        });

        precoDescricao.setText("Telefone:");

        telefoneEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneEntradaActionPerformed(evt);
            }
        });

        qtdDescricao.setText("Email:");

        voltar1.setText("Voltar");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });

        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        emailEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEntradaActionPerformed(evt);
            }
        });

        nomeDescricao1.setText("Endereco:");

        enderecoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nomeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(precoDescricao)
                                        .addGap(2, 2, 2)
                                        .addComponent(telefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fornecedorDescricao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cpfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(qtdDescricao)
                                .addGap(3, 3, 3)
                                .addComponent(emailEntrada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeDescricao1)
                                .addGap(3, 3, 3)
                                .addComponent(enderecoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addComponent(Enviar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(codigoDescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(codigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nomeDescricao))
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precoDescricao)
                    .addComponent(telefoneEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedorDescricao)
                    .addComponent(cpfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Enviar)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(nomeDescricao1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enderecoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtdDescricao))
                        .addContainerGap(24, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigoDescricao)
                        .addComponent(codigoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(nomeDescricao)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEntradaActionPerformed

    private void nomeEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeEntradaActionPerformed

    private void cpfEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfEntradaActionPerformed

    private void telefoneEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneEntradaActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        GerenciarFornecedor gp = new GerenciarFornecedor(controller);
        this.inicializarCena(gp, this);
    }//GEN-LAST:event_voltar1ActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        String cpfFornecedor = cpfEntrada.getText();
        String telefone = telefoneEntrada.getText();
        String endereco = enderecoEntrada.getText();
        String nome = nomeEntrada.getText();
        String cpf = cpfEntrada.getText();
        String email = emailEntrada.getText();
       
        Fornecedores fornecedor = new Fornecedores(endereco,cpfFornecedor,nome,email,telefone);
        this.controller.adicionarFornecedor(fornecedor);
        this.voltar1ActionPerformed(evt);
        //public Fornecedores(int id,String endereco,String cpfCnpj,  String nome, String email, String celular) {
                
    }//GEN-LAST:event_EnviarActionPerformed

    private void emailEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEntradaActionPerformed

    private void enderecoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoEntradaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel codigoDescricao;
    private javax.swing.JTextField codigoEntrada;
    private javax.swing.JTextField cpfEntrada;
    private javax.swing.JTextField emailEntrada;
    private javax.swing.JTextField enderecoEntrada;
    private javax.swing.JLabel fornecedorDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nomeDescricao;
    private javax.swing.JLabel nomeDescricao1;
    private javax.swing.JTextField nomeEntrada;
    private javax.swing.JLabel precoDescricao;
    private javax.swing.JLabel qtdDescricao;
    private javax.swing.JTextField telefoneEntrada;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
