/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import simulador.compraevenda.java.Controller;
import simulador.compraevenda.java.Fachada;

/**
 *
 * @author CONDUCTOR\saulo.terceiro
 */
public class Menu extends ControllerJFrame {

    public Menu(Controller controller) {
        super(controller);
        initComponents();

    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gerenciarProdutosBotao = new javax.swing.JButton();
        gerenciarCategoriasBotao = new javax.swing.JButton();
        gerenciarPessoaFisciaBotao = new javax.swing.JButton();
        gerenciarFornecedoresBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Menu");

        gerenciarProdutosBotao.setText("Gerenciar Produtos");
        gerenciarProdutosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarProdutosBotaoActionPerformed(evt);
            }
        });

        gerenciarCategoriasBotao.setText("Gerenciar Categorias");
        gerenciarCategoriasBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarCategoriasBotaoActionPerformed(evt);
            }
        });

        gerenciarPessoaFisciaBotao.setText("Gerenciar Pessoa Fisica");

        gerenciarFornecedoresBotao.setText("Gerenciar Fornecedores");
        gerenciarFornecedoresBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarFornecedoresBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerenciarFornecedoresBotao)
                    .addComponent(gerenciarPessoaFisciaBotao)
                    .addComponent(gerenciarCategoriasBotao)
                    .addComponent(gerenciarProdutosBotao)
                    .addComponent(jLabel1))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(gerenciarProdutosBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerenciarCategoriasBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerenciarPessoaFisciaBotao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerenciarFornecedoresBotao)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerenciarProdutosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarProdutosBotaoActionPerformed
        // TODO add your handling code here:
            GerenciarProduto gp = new GerenciarProduto(this.controller);
            this.inicializarCena(gp, this);
    }//GEN-LAST:event_gerenciarProdutosBotaoActionPerformed

    private void gerenciarCategoriasBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarCategoriasBotaoActionPerformed
        // TODO add your handling code here:
        GerenciarCategorias gc = new GerenciarCategorias(this.controller);
        this.inicializarCena(gc,this);
    }//GEN-LAST:event_gerenciarCategoriasBotaoActionPerformed

    private void gerenciarFornecedoresBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarFornecedoresBotaoActionPerformed
        // TODO add your handling code here:
        GerenciarFornecedor gf = new GerenciarFornecedor(controller);
        this.inicializarCena(gf, this);
    }//GEN-LAST:event_gerenciarFornecedoresBotaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerenciarCategoriasBotao;
    private javax.swing.JButton gerenciarFornecedoresBotao;
    private javax.swing.JButton gerenciarPessoaFisciaBotao;
    private javax.swing.JButton gerenciarProdutosBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
